### ISSUE TITLE
Exceptions from async callbacks to FakeAsync are swallowed

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/fake_async#20] opened 2020-05-16 01:42 UTC
Running the following prints no diagnostic:

```dart
void main() async {
  await FakeAsync().run<Future<void>>((_) async {
    throw Exception('exception');
  });
}
```
This seems surprising, and if it's not expected to work, it doesn't seem obvious from the `FakeAsync` documentation.

This also seems like a footgun, especially since `FakeAsync` is likely to be used in a `test()` callback, where `expect()` calls can appear to pass when they actually fail.

**Comment by matejdro** [comment] 2020-11-25 19:34
Any workaround for this?

**Comment by natebosch** [comment] 2020-11-26 04:59
The problem with this specific example is that there is nothing to call `flushMicrotasks()` to continue the execution. The callback passed is `async`, so the `throw` sets up a `Future` that will complete as an error, but hasn't completed yet. It's in the `FakeAsync` zone, so unless something calls `flushMicrotasks()` or `elapse()` it never will complete. The VM is able to recognize that there are no further events on the root microtask, and no timers or open ports, so it shuts down.

Errors are surfaced. It's not elegant, but you can see this happening by making sure `FakeAsync.flushMicrotasks()` is called. Scheduling something in the root zone works around the fact that nothing scheduled in the FakeAsync zone will progress without that call.

```dart
void main() async {
  await FakeAsync().run<Future<void>>((f) async {
    Zone.root.run(() async {
      await Future((){});
      f.flushMicrotasks();
    });
    throw Exception('exception');
  });
}
```


Is there a step higher we can move towards a real world scenario where this is a problem, without involving a full project? Can you explain where you saw this as an issue?

**Comment by jamesderlin** [comment] 2021-01-29 04:11
> Is there a step higher we can move towards a real world scenario where this is a problem, without involving a full project? Can you explain where you saw this as an issue?

Ugh, it was awhile ago and don't remember how I ran into this.  I *think* I was trying to force a test in the Flutter tool to fail and got really confused when I couldn't.

**Comment by matejdro** [comment] 2021-01-29 07:09
> Can you explain where you saw this as an issue?

Well the issue is that throwing an exception will stop the execution of the code:

```dart
void main() async {
  await FakeAsync().run<Future<void>>((f) async {
    scheduleSomeAsyncTask();
    callSomeMethodThatThrowsException();
    f.flushMicrotasks();
    ...
  });
}
```

Even though my code is supposed to execute `flushMicrotasks`, the code before it throws exception which means that `flushMicrotasks` will not get executed and exception will get swallowed.

**Comment by natebosch** [comment] 2021-02-01 18:11
> When used in tests, which will cause the test to be registered as false positive.

The test runner has timeouts to catch this.

I'm going to close this issue for now. I don't know if we'll find an impactful way to surface potential mistakes like this without taking away too much power.

**Closed by natebosch** 2021-02-01 18:11 UTC

**Comment by matejdro** [comment] 2021-02-01 18:15
What do you mean it has timeouts? How is one supposed  to write test like that?

```
void main() async {
  await FakeAsync().run<Future<void>>((f) async {
    doSomeAsyncStuff();
    f.elapse(...);
    assert(...)
    ...
  });
}
```

How can we detect that assertion inside that test failed?

**Comment by natebosch** [comment] 2021-02-01 18:25
> How is one supposed to write test like that?


```dart
void main() {
  test('some test', () async {
    // This test will fail with a timeout.
    await FakeAsync().run<Future<void>>((f) async {
      scheduleSomeAsyncTask();
      callSomeMethodThatThrowsException();
      f.flushMicrotasks();
      ...
    });
  });
}
```

**Comment by jamesderlin** [comment] 2021-02-01 18:25
@matejdro's comment reminds me: I think I encountered this adding `assert`s to a test in `flutter_tools`, and the `assert`s never tripped.  IIRC, the test passed and did not time out.

**Comment by natebosch** [comment] 2021-02-01 18:34
> IIRC, the test passed and did not time out.

If we can find a minimal repro of this and we believe it's a common mistake we could investigate patterns which make it easier to avoid.

Without knowing what are the specific mistakes, and how widespread they are, it's tough to know where to put our energy.

Any tool which allows you to prevent or delay async work is going to carry risk of making some things that should happen, never happen. I'm definitely open to improving the usability where we can, but this may point more at the fact that we are overusing this dangerous tool, than that the tool needs to be blunted.

**Comment by matejdro** [comment] 2021-02-01 18:39
I'm new with flutter so I'm just trying to apply concepts from another languages. I'm used to this pattern:

1. Start async task
2. Advance the time to trigger whatever time-sensitive thing is in the task
3. Use `expect` to validate that task properly executed.

What would be the flutter-y way to do this?
